# Generated by Django 2.2.5 on 2021-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
