# Generated by Django 2.2.5 on 2021-04-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210409_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content.ContentType'),
        ),
    ]
