# Generated by Django 2.2.5 on 2021-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210411_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='description',
        ),
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
