# Generated by Django 2.2.5 on 2021-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210411_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
